### ISSUE TITLE
.bidsignore in KUL_dcm2bids.sh

### ISSUE THREAD

**Issue by lukasvo76** [treanus/KUL_NIS#31]
Hi Stefan,

I have a small suggestion re lines 1376- in KUL_dcm2bids.sh, the code block creating the .bidsignore file.
This is handy, except for the fact that in case you want to add study-specific lines to your .bidsignore file (as I had done prior to running KUL_dcm2bids.sh on my first subject), they seem to disappear after running the script because the .bidsignore file gets overwritten, and this happens again after running every subject.

If I understand things correctly, this can easily be changed by replacing > with >> on line 1383, as this would append the new lines to any existing .bidsignore file rather than overwrite the existing file? I tested this locally (without adding nor committing) and it works, but the problem then is that it appends the same lines to .bidsignore after running the script for each subject, which does not harm, but is not very clean? Hence, another option may be to check whether .bidsignore already exists and then decide based on that whether to append or newly create? Not sure whether or how line 1379 does that? It does not seem to do it in my hands.

Or maybe you see a different option?

I wanted to check by you before branching and submitting a pull request, but happy to do so if you like?!

Other than this small issue, the script works great - really helpful!

Best wishes,

Lukas

**Comment by treanus** [comment]
Hi Lukas,

thanks for your suggestion, which is great.

The best way to go forward is:
- you fork
- then you change code in your own fork, and 
- then making a PR.

Then I can incorporate your change here.

However, I added you to as a contributer, since you gave a lot of feedback. The invite should be in your inbox.

Adding you as a contributer, should allow you to pull the PR (which you made yourself in your fork) into this repository.

Let me know if this works...

KR,
S

**Comment by treanus** [comment]
BTW, 

of course pull your PR to the "development' brach, or the another branch that you can create. 
NOT to the master branch please!
Once tested and stable I can update master from 'develpoment".

Thx.

**Comment by treanus** [comment]
Hi Lukas,

For this issue, 
I did the change https://github.com/treanus/KUL_NIS/commit/86ceb032ef477ae3ff69b8c94eee90e38da493ba
Can you pull development, and see if this is correct?

For future bugs/improvements:
1/ fork
2/ change and test at will
3/ create PR

Thx

**Comment by lukasvo76** [comment]
Hi Stefan,

Thanks a lot, and the workflow for future issues is noted!

This works fine, but it will add the same lines to .bidsignore repeatedly after every run of the script on every subject now, which is not a huge issue, but something you may want to prevent possibly, by building in a check whether those lines are already in .bidsignore?

Sorry I can't do it myself, would be an option in Matlab, but not (yet) in shell I am afraid!

Lukas
